#! /bin/sh
### BEGIN INIT INFO
# Provides:		epmd
# Required-Start:	$syslog $remote_fs
# Required-Stop:	$syslog $remote_fs
# Should-Start:		$local_fs
# Should-Stop:		$local_fs
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	epmd - Erlang port monitor daemon
# Description:		epmd - Erlang port monitor daemon
### END INIT INFO


PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/local/lib/otp-24/bin/epmd 
DAEMON_ARGS=
NAME=epmd
DESC=epmd

RUNDIR=/run/epmd
PIDFILE=$RUNDIR/epmd.pid

test -x $DAEMON || exit 0

if [ -r /etc/default/$NAME ]
then
	. /etc/default/$NAME
fi

. /lib/lsb/init-functions

set -e

if [ "$(id -u)" != "0" ]
then
	log_failure_msg "Must be run as root."
	exit 1
fi

case "$1" in
    start)
	mkdir -p $RUNDIR
	touch $PIDFILE
	chown epmd:epmd $RUNDIR $PIDFILE
	chmod 755 $RUNDIR
	echo -n "Starting $DESC: "
	if $DAEMON -daemon
	then
	    pgrep -f "${DAEMON}" > $PIDFILE
	    echo "$NAME"
	else
	    rm -f $PIDFILE
	    echo "failed"
	fi
	;;
  stop)
	echo -n "Stopping $DESC: "

	if $DAEMON -kill
	then
		echo "$NAME."
	else
		echo "failed"
	fi
	rm -f $PIDFILE
	sleep 1
	;;

  restart|force-reload)
	${0} stop
	${0} start
	;;

  status)
	status_of_proc -p ${PIDFILE} ${DAEMON} ${NAME}
	;;

  *)
	echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload|status}" >&2
	exit 1
	;;
esac

exit 0
